// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// TISP_inner
List TISP_inner(const Eigen::Map<Eigen::MatrixXd>& X_affinity, const Eigen::Map<Eigen::VectorXd>& y_affinity, const Eigen::Map<Eigen::VectorXd>& beta_init, const double& y_sc, const double& lambda, const int& q, double& step_size, const bool& accelerate, const bool& line_search, const double& ls_beta, const double& ls_eps, const int& ls_maxit, const double& eta, const std::string& thresh_type, const std::string& tol_type, const int& maxit, const double& eps, const std::string& ls_type);
RcppExport SEXP _SPAS_TISP_inner(SEXP X_affinitySEXP, SEXP y_affinitySEXP, SEXP beta_initSEXP, SEXP y_scSEXP, SEXP lambdaSEXP, SEXP qSEXP, SEXP step_sizeSEXP, SEXP accelerateSEXP, SEXP line_searchSEXP, SEXP ls_betaSEXP, SEXP ls_epsSEXP, SEXP ls_maxitSEXP, SEXP etaSEXP, SEXP thresh_typeSEXP, SEXP tol_typeSEXP, SEXP maxitSEXP, SEXP epsSEXP, SEXP ls_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type X_affinity(X_affinitySEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type y_affinity(y_affinitySEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type beta_init(beta_initSEXP);
    Rcpp::traits::input_parameter< const double& >::type y_sc(y_scSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const int& >::type q(qSEXP);
    Rcpp::traits::input_parameter< double& >::type step_size(step_sizeSEXP);
    Rcpp::traits::input_parameter< const bool& >::type accelerate(accelerateSEXP);
    Rcpp::traits::input_parameter< const bool& >::type line_search(line_searchSEXP);
    Rcpp::traits::input_parameter< const double& >::type ls_beta(ls_betaSEXP);
    Rcpp::traits::input_parameter< const double& >::type ls_eps(ls_epsSEXP);
    Rcpp::traits::input_parameter< const int& >::type ls_maxit(ls_maxitSEXP);
    Rcpp::traits::input_parameter< const double& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type thresh_type(thresh_typeSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type tol_type(tol_typeSEXP);
    Rcpp::traits::input_parameter< const int& >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const double& >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type ls_type(ls_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(TISP_inner(X_affinity, y_affinity, beta_init, y_sc, lambda, q, step_size, accelerate, line_search, ls_beta, ls_eps, ls_maxit, eta, thresh_type, tol_type, maxit, eps, ls_type));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SPAS_TISP_inner", (DL_FUNC) &_SPAS_TISP_inner, 18},
    {NULL, NULL, 0}
};

RcppExport void R_init_SPAS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
