# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

TISP_inner <- function(X_affinity, y_affinity, beta_init, y_sc, lambda, q, step_size, accelerate = TRUE, line_search = TRUE, ls_beta = 1.5, ls_eps = 1e-10, ls_maxit = 100L, eta = 1e-4, thresh_type = "quantile_ridge", tol_type = "beta", maxit = 2000L, eps = 1e-5, ls_type = "forward") {
    .Call('_SPAS_TISP_inner', PACKAGE = 'SPAS', X_affinity, y_affinity, beta_init, y_sc, lambda, q, step_size, accelerate, line_search, ls_beta, ls_eps, ls_maxit, eta, thresh_type, tol_type, maxit, eps, ls_type)
}

